[project]
name = "reveal-audit"
authors = ["Your Name <your.email@example.com>"]
description = "A blockchain-powered health metrics tracking and auditing platform"
telemetry = false
requirements = []
[contracts.health-metrics]
path = "contracts/health-metrics.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
